### ISSUE TITLE
secretGenreButton

### ISSUE THREAD

**Issue by yutaroyoshikawa** [yutaroyoshikawa/grady#33]
## overview
topページにあるシークレット映画のジャンルごとのボタン
propsで渡したtextをパッケージ表示に、valueをリンクに使って欲しいです。

## props
| property | type | description |
|:---------|------|------------:|
| text | String | ジャンル名 |
| value | String | 内部値 |

**Comment by Micchili** [comment]
secretCardとsecretGenreButton、どっちが名前正しいの？
